return {
    name = "tools.prefab_editor",
    dependencies = {
        "ant.asset",
        "ant.compile_resource",
        "ant.editor",
        "ant.general",
        "ant.geometry",
        "ant.hwi",
        "ant.imgui",
        "ant.rmlui",
        "ant.math",
        "ant.render",
        "ant.serialize",
        "ant.camera",
        "ant.animation",
        "ant.collision",
        "ant.sky",
        --"ant.effekseer",
        -- "ant.audio",
        "ant.inputmgr",
        "ant.ecs",
        "ant.subprocess",
        "ant.settings",
        "ant.objcontroller",
        "ant.terrain",
        "ant.efk",
        "ant.modifier"
    },
    entry = "editor.callback",
}
