modules = {
    "libs/inputmgr/message_system.lua",
    "libs/serialize/serialize_component.lua",
    "libs/serialize/serialize_system.lua",
    "libs/serialize/serialize_luatabletext.lua",
    "libs/scene/hierarchy.lua",
    "libs/scene/filter_component.lua",
    "libs/scene/filter_system.lua",
    "libs/render/constant_system.lua",
    "libs/render/add_entity_system.lua",	-- for test
    "libs/render/editor/general_editor_entities.lua",	-- editor			
    "libs/render/editor/editable_hierarchy.lua",
    "libs/render/editor/build_hierarchy_system.lua",
    "libs/render/window_component.lua",
    "libs/render/components/general.lua",			
    "libs/render/math3d/math_component.lua",			
    "libs/render/camera/camera_component.lua",
    "libs/render/camera/camera_controller.lua",
    "libs/render/view_system.lua",
    "libs/render/entity_rendering_system.lua",
    "libs/render/pick/pickup_system.lua",
    "libs/render/pick/obj_trans_controller.lua",
    "libs/render/end_frame_system.lua",
}