/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform osx --type fragment -p metal -f mesh/fs_mesh.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/macos/metal/fs_mesh.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders
/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform osx --type vertex -p metal -f mesh/vs_mesh.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/macos/metal/vs_mesh.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders

/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform osx --type fragment -p metal -f fullquad/fs_quad.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/macos/metal/fs_quad.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders
/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform osx --type vertex -p metal -f fullquad/vs_quad.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/macos/metal/vs_quad.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders

/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform ios --type fragment -p metal -f mesh/fs_mesh.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/ios/metal/fs_mesh.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders
/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform ios --type vertex -p metal -f mesh/vs_mesh.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/ios/metal/vs_mesh.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders

/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform ios --type fragment -p metal -f fullquad/fs_quad.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/ios/metal/fs_quad.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders
/Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/bin/macos/debug/shaderc --platform ios --type vertex -p metal -f fullquad/vs_quad.sc -o /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/test/native_bgfx/pkg/ant.test.native_bgfx/shaders/bin/ios/metal/vs_quad.bin --depends -i /Users/ejoy-ant-mac-mini/code/vaststars2/3rd/ant/pkg/ant.resources/shaders
