include common.mk

IMGLIB = $(IUPSRC)/srcimglib

SRC = iup_image_library.c iup_imglib_circleprogress.c

SRC += iup_imglib_basewin32x32.c
SRC += iup_imglib_logos48x48.c iup_imglib_logos32x32.c
SRC += iup_imglib_iconswin48x48.c

SRC :=  $(addprefix $(IMGLIB)/, $(SRC))

all : iupluaimglib.dll

iupluaimglib.dll :  $(SRC) $(IUPSRC)/srclua5/iuplua_imglib.c
	$(CC) --shared -o $@ $^ -I$(IMGLIB) -I$(IUPSRC)/include -I$(IUPSRC)/src $(LUAINC) $(LUALIB) -L. -lluaiup
