local runtime_config = {
    policy = {
        "ant.animation|animation",
        "ant.animation|state_machine",
        "ant.animation|ozzmesh",
        "ant.animation|ozz_skinning",
        "ant.animation|skinning",
        "ant.serialize|serialize",
        "ant.bullet|collider",
        "ant.sky|procedural_sky",
        "ant.render|name",
        "ant.render|mesh",
        "ant.render|shadow_cast",
        "ant.render|render",
        "ant.render|bounding_draw",
        "ant.render|debug_mesh_bounding",
        "ant.render|light.directional",
        "ant.render|light.ambient",
        "ant.scene|hierarchy",
        "ant.scene|ignore_parent_scale",
        --editor
        "ant.character|character",
        "ant.objcontroller|select",
    },
    system = {
        "ant.test.features|init_loader",
    },
    pipeline = {
        { name = "init",
            "init",
            "post_init",
        },
        { name = "update",
            "start",
            "timer",
            "data_changed",
            "scene_update",
            {name = "collider",
                "update_collider_transform",
                "update_collider",
            },
            { name = "animation",
                "animation_state",
                "sample_animation_pose",
                "ik",
                "skin_mesh",
                },
                { name = "sky",
                    "update_sun",
                    "update_sky",
                },
                "widget",
                { name = "render",
                    "shadow_camera",
                    "load_render_properties",
                    "filter_primitive",
                    "make_shadow",
                    "debug_shadow",
                    "cull",
                    "render_commit",
                    { name = "postprocess",
                        "bloom",
                        "tonemapping",
                        "combine_postprocess",
                    }
                },
            -- editor
            "camera_control",
            "lock_target",
            "pickup",
            "update_editable_hierarchy",
            { name = "ui",
                    "ui_start",
                    "ui_update",
                "ui_end",
            },
            "end_frame",
            "final",
        },
    },
}
local editor_config = {
    policy = {
        "ant.animation|animation",
        "ant.animation|state_machine",
        "ant.animation|ozzmesh",
        "ant.animation|ozz_skinning",
        "ant.animation|skinning",
        "ant.serialize|serialize",
        "ant.bullet|collider",
        "ant.sky|procedural_sky",
        "ant.render|name",
        "ant.render|mesh",
        "ant.render|shadow_cast",
        "ant.render|render",
        "ant.render|bounding_draw",
        "ant.render|debug_mesh_bounding",
        "ant.render|light.directional",
        "ant.render|light.ambient",
        "ant.scene|hierarchy",
        "ant.scene|ignore_parent_scale",
        "ant.imgui|gizmo_object",
        -- "ant.testimgui|"
        -- "ant.hierarchy.offline|",
        --editor
        "ant.test.features|character",
        "ant.objcontroller|select",
    },
    system = {
        "ant.test.features|init_loader",
        "ant.objcontroller|pickup_system",
        "ant.hierarchy.offline|build_hierarchy_system",
        "ant.imgui|editor_watcher_system",
        "ant.imgui|editor_operate_gizmo_system",
        "ant.imgui|editor_tool_system",
        "ant.imgui|world_profile_system",
        "ant.scene|visible_system",
        "ant.render|viewport_detect_system",
    },
    pipeline = {
        { name = "init",
            "init",
            "post_init",
        },
        { name = "update",
            "start",
            "timer",
            "data_changed",
            "scene_update",
            {name = "collider",
                "update_collider_transform",
                "update_collider",
            },
            { name = "animation",
                "animation_state",
                "sample_animation_pose",
                "ik",
                "skin_mesh",
                },
                { name = "sky",
                    "update_sun",
                    "update_sky",
                },
                "widget",
                "update",
                { name = "render",
                    "shadow_camera",
                    "load_render_properties",
                    "filter_primitive",
                    "make_shadow",
                    "debug_shadow",
                    "cull",
                    "render_commit",
                    { name = "postprocess",
                        "bloom",
                        "tonemapping",
                        "combine_postprocess",
                    }
                },
            -- editor
            "camera_control",
            "lock_target",
            "pickup",
            "editor_update",
            "update_editable_hierarchy",
            -- { name = "ui",
            --         "ui_start",
            --         "ui_update",
            --     "ui_end",
            -- },
            "after_update",
            "end_frame",
            "final",
        }
    }
}
--animation test
-- local editor_config = {
--     policy = {
--         "ant.animation|animation",
--         "ant.animation|state_machine",
--         "ant.animation|ozzmesh",
--         "ant.animation|ozz_skinning",
--         "ant.animation|skinning",
--         "ant.serialize|serialize",
--         "ant.render|mesh",
--         "ant.render|render",
--         "ant.render|name",
--         "ant.render|light.directional",
--         "ant.render|light.ambient",
--         --
--         --editor
--         "ant.imgui|gizmo_object",
--         -- "ant.testimgui|"
--         -- "ant.hierarchy.offline|",
--         -- "ant.test.features|character_controller",
--         "ant.objcontroller|select",
--         "ant.scene|hierarchy",
--     },
--     system = {
--         "ant.test.animation|init_loader",
--         "ant.objcontroller|pickup_system",
--         "ant.hierarchy.offline|build_hierarchy_system",
--         "ant.imgui|editor_watcher_system",
--         "ant.imgui|editor_operate_gizmo_system",
--         "ant.imgui|editor_tool_system",
--         "ant.imgui|world_profile_system",
--         "ant.scene|visible_system",
--         "ant.render|viewport_detect_system",
--     },
--     pipeline = {
--         { name = "init",
--             "init",
--             "post_init",
--         },
--         { name = "update",
--             "timer",
--             "data_changed",
--             "scene_update",
--             {name = "collider",
--                 "update_collider_transform",
--                 "update_collider",
--             },
--             { name = "animation",
--                 "animation_state",
--                 "sample_animation_pose",
--                 "skin_mesh",
--             },
--             { name = "sky",
--                 "update_sun",
--                 "update_sky",
--             },
--             "widget",
--             "update",
--             { name = "render",
--                 "shadow_camera",
--                 "load_render_properties",
--                 "filter_primitive",
--                 "make_shadow",
--                 "debug_shadow",
--                 "cull",
--                 "render_commit",
--                 { name = "postprocess",
--                     "bloom",
--                     "tonemapping",
--                     "combine_postprocess",
--                 }
--             },
--             "camera_control",
--             "lock_target",
--             "pickup",
--             "update_editable_hierarchy",
--             "editor_update",
--             { name = "ui",
--                 "ui_start",
--                 "ui_update",
--                 "ui_end",
--             },
--             "after_update",
--             "end_frame",
--             "final",
--         }
--     }
-- }

return {
    runtime = runtime_config,
    editor = editor_config
}